# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: music to your ears
email: atsushieno (guess domains)
description: > # this means to ignore newlines until "baseurl:"
  Blog posts, mostly about software engineering and music tech, by Atsushi Eno. Comments to me are welcomed as [github issues](https://github.com/atsushieno/atsushieno.github.io/issues).
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: atsushi_eno
github_username:  atsushieno

# Build settings
markdown: kramdown
