---
title: music to your ears
timezone: Asia/Tokyo
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: atsushieno (guess domains)
description: Blog posts, mostly about software engineering and music tech, by Atsushi Eno.
twitter_username: atsushieno
github_username: atsushieno
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]
