---
title: music to your ears
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: atsushieno (guess domains)
description: 'Blog posts, mostly about software engineering and music tech, by Atsushi
  Eno. Comments to me are welcomed as [github issues](https://github.com/atsushieno/atsushieno.github.io/issues).

'
baseurl: ''
url: http://yourdomain.com
twitter_username: atsushi_eno
github_username: atsushieno
markdown: kramdown
